apiVersion: v1
kind: ConfigMap
metadata:
  name: das-server-filebeat-config
  namespace: das
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /data/logs/das.log*${MY_POD_NAME}*
      ignore_older: 1h
      scan_frequency: 10s
      backoff: 5s
      max_backoff: 10s
    output.console:
      codec.format:
        string: '%{[message]} - Podname=${MY_POD_NAME}}'
        pretty: false
    queue.mem:
      events: 65536
    logging.metrics.enabled: false

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: das-server-promtail
  labels:
    app: das-server-promtail
  namespace: das
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    scrape_configs:
    - job_name: das-server
      static_configs:
      - targets:
          - das-logs
        labels:
          job: das-logs
          __path__: /data/logs/das.log*
