apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ms-output-mongo.fullname" . }}
  labels:
    {{- include "ms-output-mongo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount}}     
  {{- end }}
  selector:
    matchLabels:
      {{- include "ms-output-mongo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ms-output-mongo.selectorLabels" . | nindent 8 }}
        {{- if .Values.environment.preprod}}
        env: k8s-preprod
        {{- end }}
        {{- if .Values.environment.prod}}
        env: k8s-prod
        {{- end }}
        {{- if .Values.environment.test}}
        env: k8s
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ms-output-mongo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          tty: true
          stdin: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
           - containerPort: {{ .Values.service.port }}
             name: {{ .Values.service.name }}
             protocol: {{ .Values.service.protocol }}
           - containerPort: {{ .Values.serviceMon.port }}
             name: {{ .Values.serviceMon.name }}
             protocol: {{ .Values.serviceMon.protocol }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: secrets
            mountPath: /etc/secrets
            readOnly: true
{{- if or .Values.environment.prod .Values.environment.preprod }}
          - name: ms-output-mongo-data
            mountPath: /data/mongodb
{{- end }}
      volumes:
      - name: secrets
        secret:
          secretName: ms-output-mongo-secrets
{{- if or .Values.environment.prod .Values.environment.preprod }}
      - name: ms-output-mongo-data
        persistentVolumeClaim:
            claimName: ms-output-claim
{{- end }}
