kind: ConfigMap
apiVersion: v1
metadata:
  name: ms-transferor
  labels:
    app: ms-transferor
  namespace: dmwm
data:
  setup-certs-and-run.sh: |
    #!/bin/bash
    cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    su  -c "cd /data && /data/run.sh" --preserve-environment _reqmgr2ms
