apiVersion: v1
kind: ConfigMap
metadata:
  name: reqmgr2-tasks-filebeat-config
  namespace: dmwm
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /data/srv/logs/reqmgr2/*${MY_POD_NAME}*.log
      ignore_older: 1h
      scan_frequency: 10s
      backoff: 5s
      max_backoff: 10s
    output.console:
      codec.format:
        string: '%{[message]} - Podname=${MY_POD_NAME}'
        pretty: false
    queue.mem:
      events: 65536
    logging.metrics.enabled: false
---
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: reqmgr2-tasks
  labels:
    app: reqmgr2-tasks
  namespace: dmwm
data:
  setup-certs-and-run.sh: |
    #!/bin/bash
    sudo cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    #su  -c "cd /data && /data/run.sh" --preserve-environment _reqmgr2
    cd /data && /data/run.sh
---
