apiVersion: v1
kind: Service
metadata:
  name: {{ include "das-mongo.fullname" . }}
  labels:
    {{- include "das-mongo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port}}
    name: {{ .Values.service.name }}
  - port: {{ .Values.serviceMon.port }}
    name: {{ .Values.serviceMon.name }}
    targetPort: {{ .Values.serviceMon.port}}
  selector:
    {{- include "das-mongo.selectorLabels" . | nindent 4 }}
