apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "imagebot.fullname" . }}
  labels:
  {{- include "imagebot.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: imagebot-account
  namespace: http
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: imagebot
