apiVersion: v1
kind: Service
metadata:
  name: {{ include "imagebot.fullname" . }}
  labels:
    {{- include "imagebot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  type: NodePort
  selector:
    {{- include "imagebot.selectorLabels" . | nindent 4 }}
